#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
"""Converts a CrashMonkey/ACE J-lang workload into a POSIX sh script.

The output runs inside the guest with CWD = a fresh directory on the
recorded test disk, using only tools present in the xfstests conformance
runtime (xfs_io, coreutils). Ops outside the supported subset (falloc,
mmapwrite, xattrs, dwrite) make the converter fail loudly — filter the
corpus first (run_matrix.sh does).

ACE flattens paths in op arguments (`Afoo` means `A/foo`); the standard
seq-1 name table is fixed, so it is hardcoded here, matching
crashmonkey/ace/xfstestAdapter.py.
"""

import sys

# The fixed ACE name table (see the `# define` block of any seq-1 J-lang
# file). `test` is the workload root = the script's CWD.
NAMES = {
    "test": ".",
    "A": "A",
    "B": "B",
    "AC": "A/C",
    "foo": "foo",
    "bar": "bar",
    "Afoo": "A/foo",
    "Abar": "A/bar",
    "Bfoo": "B/foo",
    "Bbar": "B/bar",
    "ACfoo": "A/C/foo",
    "ACbar": "A/C/bar",
}


def path(name: str) -> str:
    try:
        return NAMES[name]
    except KeyError:
        raise SystemExit(f"unknown ACE name: {name}")


def convert(lines):
    out = [
        "#!/bin/sh",
        "# Generated by jlang2sh.py — do not edit.",
        "set -eu",
    ]
    in_run = False
    for raw in lines:
        line = raw.strip()
        if line.startswith("# run"):
            in_run = True
            continue
        if not in_run or not line or line.startswith("#"):
            continue
        op, *args = line.split()
        if op in ("open", "creat"):
            # Creation matters for the crash surface; fd bookkeeping does not
            # (persistence points are re-opened by name via xfs_io).
            out.append(f'[ -e "{path(args[0])}" ] || touch "{path(args[0])}"')
        elif op == "opendir" or op == "close":
            pass
        elif op == "mkdir":
            out.append(f'mkdir -p "{path(args[0])}"')
        elif op == "rmdir":
            out.append(f'rmdir "{path(args[0])}"')
        elif op == "write":
            name, off, length = args[0], args[1], args[2]
            out.append(f'xfs_io -f -c "pwrite -S 0x22 {off} {length}" "{path(name)}"')
        elif op == "truncate":
            out.append(f'xfs_io -f -c "truncate {args[1]}" "{path(args[0])}"')
        elif op == "link":
            out.append(f'ln "{path(args[0])}" "{path(args[1])}"')
        elif op in ("unlink", "remove"):
            out.append(f'rm -f "{path(args[0])}"')
        elif op == "rename":
            out.append(f'mv "{path(args[0])}" "{path(args[1])}"')
        elif op == "fsync":
            out.append(f'xfs_io -r -c "fsync" "{path(args[0])}"')
        elif op == "fdatasync":
            out.append(f'xfs_io -r -c "fdatasync" "{path(args[0])}"')
        elif op == "sync":
            out.append("sync")
        elif op == "checkpoint":
            out.append(f"# checkpoint {args[0]}")
        else:
            raise SystemExit(f"unsupported op: {op}")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("usage: jlang2sh.py <j-lang-file>")
    with open(sys.argv[1]) as f:
        sys.stdout.write(convert(f.readlines()))
